#!/bin/bash

# -------------------------------
# Exit Codes
# 0 -> Success
# 1 -> Incorrect arguments
# 2 -> File does not exists
# 3 -> File not readable

# validating argument count
if [ "$#" -ne 1 ]
then 
	echo "Error: No arguments passed"
	exit 1
fi

LOG_FILE="$1"
SUMMARY_FILE="summary.txt"

# checking whether log file exists 
if [ ! -f "$LOG_FILE" ]
then
	echo "Error: log file not found"
	exit 2
fi

# checking whether log file is readable
if [ ! -r "$LOG_FILE" ]
then 
	echo "Error: log file not readable"
	exit 3
fi

LOG_LC=$(wc -l < "$LOG_FILE")
read ERROR_WC WARNING_WC < <(
awk '
{
	level = toupper($3)
	if (level == "ERROR") error++
	else if (level == "WARNING") warning++
}
END { print error, warning }
' "$LOG_FILE"
)
# Extract top 3 frequent words
TOP_WORDS=$(awk '
{
    for (i = 4; i <= NF; i++) {
        word = tolower($i)
        if (word !~ /^[0-9]+$/) {
            freq[word]++
        }
    }
}
END {
    for (w in freq)
        printf "%s %d\n", w, freq[w]
}
' "$LOG_FILE" | sort -k2 -nr | head -3 | \
awk '{printf "%d. %-15s - %s\n", NR, $1, $2}')

{
echo "======================================="
echo "           LOG SUMMARY REPORT          "
echo "======================================="

echo "Input File         : $LOG_FILE"
echo "Generated On       : $(date "+%Y-%m-%d %H-%M-%S")"
echo "Generated By       : $(basename "$0")"

echo "---------------------------------------"
echo "BASIC STATISTICS                       "
echo "---------------------------------------"
echo "Total Lines        : ${LOG_LC}"
echo "ERROR Count        : ${ERROR_WC}"
echo "WARNING Count      : ${WARNING_WC}"

echo "---------------------------------------"
echo "TOP 3 FREQUENT WORDS                   "
echo "---------------------------------------"
echo "$TOP_WORDS"
echo "---------------------------------------"
echo "END OF REPORT                          "
echo "---------------------------------------"

} > "$SUMMARY_FILE"

if [ "$?" -eq 0 ]
then
	echo "Summary file generated Successfully"
fi

