#!/bin/bash

# -------------------------------
# Exit Codes
# 0 -> Success
# 1 -> Incorrect arguments
# 2 -> File does not exists
# 3 -> File not readable

# validating argument count
if [ "$#" -ne 1 ]
then 
	echo "Error: No arguments passed"
	exit 1
fi

LOG_FILE="$1"
SUMMARY_FILE="summary.txt"

# checking whether log file exists 
if [ ! -f "$LOG_FILE" ]
then
	echo "Error: log file not found"
	exit 2
fi

# checking whether log file is readable
if [ ! -r "$LOG_FILE" ]
then 
	echo "Error: log file not readable"
	exit 3
fi

LOG_LC=$(wc -l < "$LOG_FILE")
ERROR_WC=$(grep -c ERROR "$LOG_FILE")
WARNING_WC=$(grep -c WARNING "$LOG_FILE")

{
echo "======================================="
echo "            LOG SUMMARY                "
echo "======================================="

echo "Input File         : $LOG_FILE"
echo "Generated On       : $(date "+%Y-%m-%d %H-%M-%S")"
echo "Generated By       : monitor.sh"

echo "---------------------------------------"
echo "          Basic Statistics             "
echo "---------------------------------------"
echo "Total Lines        : ${LOG_LC}"
echo "ERROR Count        : ${ERROR_WC}"
echo "WARNING Count      : ${WARNING_WC}"

echo "---------------------------------------"
echo "            End of Report              "
echo "---------------------------------------"

} > "$SUMMARY_FILE"

if [ "$?" -eq 0 ]
then
	echo "Summary file generated Successfully"
fi

